server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/f1betting
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: your-secret-key
  expiration: 36000000

logging:
  level:
    org.springframework.security: DEBUG

rabbitmq:
  queue:
    eventOutcome: event-outcome-queue
  exchange:
    eventOutcome: event-outcome-exchange
  routingKey:
    eventOutcome: event.outcome

openf1:
  api:
    key: openf1-key
