server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/f1betting}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: ${JWT_SECRET:your-secret-key}
  expiration: ${JWT_EXPIRATION:36000000}

logging:
  level:
    org.springframework.security: DEBUG

rabbitmq:
  queue:
    eventOutcome: ${RABBITMQ_QUEUE:event-outcome-queue}
  exchange:
    eventOutcome: ${RABBITMQ_EXCHANGE:event-outcome-exchange}
  routingKey:
    eventOutcome: ${RABBITMQ_ROUTING_KEY:event.outcome}

openf1:
  api:
    key: ${OPENF1_API_KEY:openf1-key}


